version: '3.8'

services:
  db:
    container_name: orders_manager_db
    build:
      context: build/docker/db
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      .env

volumes:
  pg_data: